"""add device_schedule table

Revision ID: 50a6a2b75d4d
Revises: 5d8f3ffb7bcf
Create Date: 2026-06-14 13:56:36.652567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50a6a2b75d4d'
down_revision: Union[str, Sequence[str], None] = '5d8f3ffb7bcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('switch_id', sa.Integer(), nullable=False),
    sa.Column('datetime_utc', sa.DateTime(), nullable=False, comment='Hour the plan applies to, in UTC'),
    sa.Column('desired_state', sa.Boolean(), nullable=False, comment='Planned state for the hour: True=on, False=off'),
    sa.Column('price_kwh', sa.Float(), nullable=False, comment='ESIOS price for the hour in €/kWh (kept for auditing/display)'),
    sa.Column('strategy', sa.String(length=50), nullable=False, comment='Strategy that produced this row, e.g. cheapest_hours'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['switch_id'], ['smart_switch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('switch_id', 'datetime_utc', name='uq_device_schedule_switch_dt')
    )
    with op.batch_alter_table('device_schedule', schema=None) as batch_op:
        batch_op.create_index('ix_device_schedule_switch_dt', ['switch_id', 'datetime_utc'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_schedule', schema=None) as batch_op:
        batch_op.drop_index('ix_device_schedule_switch_dt')

    op.drop_table('device_schedule')
    # ### end Alembic commands ###
