"""add device_override table

Revision ID: 80acd8dc502a
Revises: 50a6a2b75d4d
Create Date: 2026-06-14 14:12:58.115206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80acd8dc502a'
down_revision: Union[str, Sequence[str], None] = '50a6a2b75d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_override',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('switch_id', sa.Integer(), nullable=False),
    sa.Column('desired_state', sa.Boolean(), nullable=False, comment='State to force while active: True=on, False=off'),
    sa.Column('until_utc', sa.DateTime(), nullable=False, comment='UTC instant the boost expires'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['switch_id'], ['smart_switch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('switch_id', name='uq_device_override_switch')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_override')
    # ### end Alembic commands ###
