"""initial

Revision ID: 925935569e67
Revises: 
Create Date: 2026-02-23 02:06:55.009831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '925935569e67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smart_switch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('switch_metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('switch_id', sa.Integer(), nullable=False),
    sa.Column('current', sa.Float(), nullable=False),
    sa.Column('voltage', sa.Float(), nullable=False),
    sa.Column('power', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['switch_id'], ['smart_switch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_switch_metric_switch_time', 'switch_metric', ['switch_id', 'recorded_at'], unique=False)
    op.create_table('tuya_switch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tuya_id', sa.String(length=50), nullable=False),
    sa.Column('local_key', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['smart_switch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tuya_switch')
    op.drop_index('ix_switch_metric_switch_time', table_name='switch_metric')
    op.drop_table('switch_metric')
    op.drop_table('smart_switch')
    # ### end Alembic commands ###
