"""change SwitchMetric types

Revision ID: db03cf8c5a30
Revises: e7d672836f09
Create Date: 2026-02-27 15:19:44.787749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db03cf8c5a30'
down_revision: Union[str, Sequence[str], None] = 'e7d672836f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('switch_metric', schema=None) as batch_op:
        batch_op.alter_column('current',
                   existing_type=sa.FLOAT(),
                   type_=sa.Integer(),
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('switch_metric', schema=None) as batch_op:
        batch_op.alter_column('current',
                   existing_type=sa.Integer(),
                   type_=sa.FLOAT(),
                   existing_nullable=False)
    # ### end Alembic commands ###
