"""add electrical meter tables

Revision ID: e16a3e415063
Revises: db03cf8c5a30
Create Date: 2026-05-31 19:37:31.745715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e16a3e415063'
down_revision: Union[str, Sequence[str], None] = 'db03cf8c5a30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()

    # SQLite's batch_alter_table recreates smart_switch (DROP + CREATE), and
    # env.py enables PRAGMA foreign_keys=ON, so the DROP cascades and deletes
    # all rows from tuya_switch and switch_metric. Save them first and restore
    # after the alter — PRAGMA foreign_keys cannot be toggled inside a transaction.
    tuya_rows = conn.execute(
        sa.text("SELECT id, tuya_id, local_key, version FROM tuya_switch")
    ).mappings().fetchall()
    metric_rows = conn.execute(
        sa.text("SELECT id, switch_id, current, voltage, power, recorded_at FROM switch_metric")
    ).mappings().fetchall()

    with op.batch_alter_table('smart_switch', schema=None) as batch_op:
        batch_op.alter_column('enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    if tuya_rows:
        conn.execute(
            sa.text(
                "INSERT INTO tuya_switch (id, tuya_id, local_key, version)"
                " VALUES (:id, :tuya_id, :local_key, :version)"
            ),
            [dict(r) for r in tuya_rows],
        )
    if metric_rows:
        conn.execute(
            sa.text(
                "INSERT INTO switch_metric (id, switch_id, current, voltage, power, recorded_at)"
                " VALUES (:id, :switch_id, :current, :voltage, :power, :recorded_at)"
            ),
            [dict(r) for r in metric_rows],
        )

    op.create_table('electrical_meter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('em_metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('em_id', sa.Integer(), nullable=False),
    sa.Column('current', sa.Integer(), nullable=False),
    sa.Column('voltage', sa.Float(precision=2), nullable=False),
    sa.Column('power', sa.Float(precision=2), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['em_id'], ['electrical_meter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('em_metric', schema=None) as batch_op:
        batch_op.create_index('ix_em_metric_time', ['em_id', 'recorded_at'], unique=False)

    op.create_table('shelly_em',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['electrical_meter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smart_switch', schema=None) as batch_op:
        batch_op.alter_column('enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    op.drop_table('shelly_em')
    with op.batch_alter_table('em_metric', schema=None) as batch_op:
        batch_op.drop_index('ix_em_metric_time')

    op.drop_table('em_metric')
    op.drop_table('electrical_meter')
    # ### end Alembic commands ###
