"""Add enabled column in SmartSwitch

Revision ID: e7d672836f09
Revises: 925935569e67
Create Date: 2026-02-24 14:55:38.012454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7d672836f09'
down_revision: Union[str, Sequence[str], None] = '925935569e67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smart_switch', sa.Column('enabled', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('smart_switch', 'enabled')
    # ### end Alembic commands ###
